include(FindPackageHandleStandardArgs)

find_package(PkgConfig QUIET)

pkg_check_modules(SINGLEAPPLICATION QUIET singleapplication)

if(NOT SINGLEAPPLICATION_LIBRARIES)
  find_library(SINGLEAPPLICATION_LIBRARY NAMES singleapplication singleapplication.dll HINTS /usr/lib /usr/lib64 /usr/lib/x86_64-linux-gnu)
  set(SINGLEAPPLICATION_LIBRARIES ${SINGLEAPPLICATION_LIBRARY})
endif(NOT SINGLEAPPLICATION_LIBRARIES)

if(NOT SINGLEAPPLICATION_INCLUDE_DIRS)
  find_path(SINGLEAPPLICATION_INCLUDE_DIR singleapplication.h HINTS /usr/include /usr/local/include /include PATH_SUFFIXES singleapplication)
  set(SINGLEAPPLICATION_INCLUDE_DIRS ${SINGLEAPPLICATION_INCLUDE_DIR})
endif(NOT SINGLEAPPLICATION_INCLUDE_DIRS)

if(SINGLEAPPLICATION_LIBRARIES AND SINGLEAPPLICATION_INCLUDE_DIRS)
  set(SINGLEAPPLICATION_FOUND 1)
endif(SINGLEAPPLICATION_LIBRARIES AND SINGLEAPPLICATION_INCLUDE_DIRS)

find_package_handle_standard_args(SingleApplication DEFAULT_MSG SINGLEAPPLICATION_LIBRARIES SINGLEAPPLICATION_INCLUDE_DIRS)
mark_as_advanced(SINGLEAPPLICATION_LIBRARIES SINGLEAPPLICATION_INCLUDE_DIRS)
